### ISSUE TITLE
Support for buffered transport?

### ISSUE THREAD

**Issue by TobiasBales** [Fitbit/thriftcli#17]
I am trying to get it to work with one of our thrift service that uses the binary protocol in combination with buffered transport. From the code it looks like it just supports framed, is that correct?

If that is correct, is this project still maintained? Then I would have a shot at implementing different transports

**Comment by vtatai** [comment]
Hello Tobias, sorry for the late response - the project is still maintained and you are welcome to submit a pull request if you have the time.
